### ISSUE TITLE
[MileStone View] MileStone View

### ISSUE THREAD

**Issue by kati-kms** [boostcamp-2020/IssueTracker-10#206]
## 설명
> 이슈에 대한 설명을 작성합니다. 담당자도 함께 작성하면 좋습니다.

마일스톤 뷰 만들기

## 체크사항
> 이슈를 close하기 위해 필요한 조건들을 체크박스로 나열합니다.

- [ ] 마일스톤 화면에서는 전체 마일스톤 목록을 표시한다.

- [ ] 마일스톤 이름과 완료일, 진행율, 열린 이슈와 닫힌 이슈 개수를 표시한다.

- [ ] 설명은 마일스톤 이름 아래 한 줄만 표시한다.

- [ ] [+] 버튼을 누르면 마일스톤 추가 화면으로 이동한다. 

- [ ] 마일스톤 셀을 선택하면 편집 화면으로 이동한다.

> 마일스톤 상세뷰

- [ ] 제목을 입력할 수 있다.

- [ ] 완료 날짜를 지정할 수 있다. (선택사항으로 안 넣어도 되야 한다)

- [ ] 넣을 경우 “yyyy-mm-dd” 형식에 맞는 문자열인지만 판단한다.

- [ ]  형식에 맞지 않을 경우 “완료날짜” Label을 빨간색으로 표시한다.

- [ ] 설명을 넣을 수 있다. (선택사항으로 안 넣어도 되야 한다)

- [ ] 초기화 버튼을 누르면 입력한 값을 모두 초기화한다.

- [ ] 저장 버튼을 누르면 입력한 값으로 저장한다.

- [ ] X 버튼을 누르면, 아무런 조건없이 창을 닫아야 한다.

## 참고자료
> 이슈를 해결하기 위해 필요한 참고자료가 있다면 추가합니다.

## 관련 논의
> 이슈에 대한 논의가 있었다면 논의 내용을 간략하게 추가합니다.
